# Generated by Django 5.1.2 on 2024-12-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
