# Generated by Django 5.1.2 on 2024-12-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_rename_reciever_notification_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
