# Generated by Django 5.1.2 on 2024-12-31 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='ChatBotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('dynamic', models.BooleanField(default=False)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbotintent')),
            ],
        ),
        migrations.AddField(
            model_name='chatbotintent',
            name='keywords',
            field=models.ManyToManyField(related_name='intents', to='chatbot.keyword'),
        ),
    ]
