# Generated by Django 5.1.2 on 2025-01-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_fallbackresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FallbackResponse',
        ),
    ]
