# Generated by Django 5.1.2 on 2024-11-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closing_hours',
            field=models.CharField(blank=True, help_text="Format: e.g., 'Sat-Sun 10am-4pm'", max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_hours',
            field=models.CharField(blank=True, help_text="Format: e.g., 'Mon-Fri 9am-5pm'", max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='return_policy',
            field=models.TextField(blank=True, help_text='Specify the return policy for the store.'),
        ),
        migrations.AddField(
            model_name='store',
            name='shipping_policy',
            field=models.TextField(blank=True, help_text='Specify the shipping policy for the store.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
