# Generated by Django 5.1.2 on 2024-11-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_store_closing_hours_store_opening_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
