# Generated by Django 5.1.2 on 2024-11-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_store_store_location_store_store_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='closing_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
