# Generated by Django 5.1.2 on 2024-12-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_store_closing_hours_alter_store_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coadmin', 'Coadmin'), ('seller', 'Seller'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
