# Generated by Django 5.1.2 on 2025-01-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_admin_dashboard', 'Can view admin dashboard')]},
        ),
    ]
