# Generated by Django 5.1.2 on 2025-01-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_options'),
        ('products', '0016_remove_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='seller_products',
            field=models.ManyToManyField(related_name='stores', to='products.product'),
        ),
    ]
