# Generated by Django 5.1.2 on 2025-01-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_store_seller_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='seller_products',
        ),
    ]
