# Generated by Django 5.1.2 on 2025-01-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_store_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='featured_image',
            field=models.ImageField(blank=True, default='store_logo/default_store_logo.jpg', null=True, upload_to='store_logo/'),
        ),
    ]
