# Generated by Django 5.1.2 on 2024-11-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.IntegerField(unique=True),
        ),
    ]
