# Generated by Django 5.1.2 on 2025-02-04 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_shoppingcart_unique_together_and_more'),
        ('products', '0016_remove_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
    ]
