# Generated by Django 5.1.2 on 2025-02-10 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_shoppingcart_color'),
        ('products', '0016_remove_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
    ]
