# Generated by Django 5.1.2 on 2024-11-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckoutuserinfo',
            name='delivery_method',
            field=models.CharField(choices=[('standard', 'Standard (3-5 business days)'), ('express', 'Express (1-2 business days)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='ordercheckoutuserinfo',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
