# Generated by Django 5.1.2 on 2024-11-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordercheckoutuserinfo_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckoutuserinfo',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordercheckoutuserinfo',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordercheckoutuserinfo',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordercheckoutuserinfo',
            name='delivery_method',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], max_length=20),
        ),
    ]
