# Generated by Django 5.1.2 on 2024-11-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordercheckoutuserinfo_delivery_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckoutuserinfo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
