# Generated by Django 5.1.2 on 2024-12-04 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordercheckoutuserinfo_status'),
        ('products', '0016_remove_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercheckoutuserinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product'),
        ),
    ]
