# Generated by Django 5.1.2 on 2025-02-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordercheckoutuserinfo_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercheckoutuserinfo',
            name='cart',
        ),
    ]
