# Generated by Django 5.1.2 on 2025-02-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_shoppingcart_color'),
        ('orders', '0008_remove_ordercheckoutuserinfo_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckoutuserinfo',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.shoppingcart'),
        ),
    ]
