# Generated by Django 5.1.2 on 2025-02-08 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordercheckoutuserinfo_cart'),
        ('products', '0016_remove_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckoutuserinfo',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
    ]
