# Generated by Django 5.1.2 on 2024-10-21 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_color_alter_product_delivery_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
    ]
