# Generated by Django 5.1.2 on 2024-10-21 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_delivery_charges_alter_product_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
