# Generated by Django 5.1.2 on 2024-10-22 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_color_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.ForeignKey(default='kg', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.weight_unit'),
        ),
    ]
