# Generated by Django 5.1.2 on 2024-10-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_weight_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dimension_unit',
            new_name='DimensionUnit',
        ),
        migrations.RenameModel(
            old_name='Weight_unit',
            new_name='WeightUnit',
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.material'),
        ),
    ]
