# Generated by Django 5.1.2 on 2024-11-15 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_store_closing_hours_store_opening_hours_and_more'),
        ('products', '0012_alter_product_depth_alter_product_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.store'),
        ),
    ]
