# Generated by Django 5.1.2 on 2024-11-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_is_published_alter_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
    ]
